entrypoint: gunicorn -b :8080 "SlothAI:create_app(conf='prod')" -w 4 -t 800
service_account: sloth-ai@appspot.gserviceaccount.com
runtime: python310
instance_class: F2
automatic_scaling:
  min_instances: 1
  max_instances: 1000
  max_concurrent_requests: 4 
inbound_services:
- warmup
